package com.test.lambda;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "profit_loss")
public class QuestionModel {

	String questionId;
	
	String bookName;

	int answer;
	
	String question;
	
	String option1;
	
	String option2;
	
	String option3;
	
	String option4;
	
	String option5;
	
	String solution;

	@DynamoDBAttribute(attributeName="answer")
	public int getAnswer() {
		return answer;
	}
	
	//@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "questionId")
	//@DynamoDBAutoGeneratedKey
	public String getQuestionId() {
		return questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@DynamoDBAttribute(attributeName="bookName")
	public String getBookName() {
		return bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}
	
	public void setAnswer(int answer) {
		this.answer = answer;
	}

	@DynamoDBAttribute(attributeName="question")
	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@DynamoDBAttribute(attributeName="option1")
	public String getOption1() {
		return option1;
	}

	public void setOption1(String option1) {
		this.option1 = option1;
	}

	@DynamoDBAttribute(attributeName="option2")
	public String getOption2() {
		return option2;
	}

	public void setOption2(String option2) {
		this.option2 = option2;
	}

	@DynamoDBAttribute(attributeName="option3")
	public String getOption3() {
		return option3;
	}

	public void setOption3(String option3) {
		this.option3 = option3;
	}

	@DynamoDBAttribute(attributeName="option4")
	public String getOption4() {
		return option4;
	}

	
	public void setOption4(String option4) {
		this.option4 = option4;
	}

	@DynamoDBAttribute(attributeName="option5")
	public String getOption5() {
		return option5;
	}

	public void setOption5(String option5) {
		this.option5 = option5;
	}

	@DynamoDBAttribute(attributeName="solution")
	public String getSolution() {
		return solution;
	}

	public void setSolution(String solution) {
		this.solution = solution;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("QuestionModel [questionId=");
		builder.append(questionId);
		builder.append(", bookName=");
		builder.append(bookName);
		builder.append(", answer=");
		builder.append(answer);
		builder.append(", question=");
		builder.append(question);
		builder.append(", option1=");
		builder.append(option1);
		builder.append(", option2=");
		builder.append(option2);
		builder.append(", option3=");
		builder.append(option3);
		builder.append(", option4=");
		builder.append(option4);
		builder.append(", option5=");
		builder.append(option5);
		builder.append(", solution=");
		builder.append(solution);
		builder.append("]");
		return builder.toString();
	}
	
	
	
	
}
